/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'

import {
  Environment,
  OrbitControls,
  OrthographicCamera,
} from '@react-three/drei'

export default function Shop(props) {
  const cameraRef = useRef(null)

  // useEffect(() => {
  //   if (!!cameraRef.current) {
  //     console.log(cameraRef.current.scale)
  //     const cameraObject = cameraRef.current
  //     gsap.to(cameraRef.current.scale, {
  //       x: 0.001,
  //       y: 0.001,
  //       z: 0.001,
  //       duration: 5,
  //     })
  //   }
  // }, [cameraRef.current])

  const move = () => {
    const tl = gsap.timeline()
    tl.add('same')
      .to(
        cameraRef.current.position,
        {
          x: 50,
          y: 4,
          z: 0,
          duration: 1,
        },
        'same'
      )
      .to(
        cameraRef.current.scale,
        {
          x: 0.5,
          y: 0.5,
          z: 0.5,
          duration: 1,
        },
        'same'
      )

    console.log(cameraRef.current.scale)
  }
  let camScale = 1
  window.addEventListener('wheel', function (e) {
    if (!!cameraRef.current.scale) {
      if (Math.sign(e.wheelDeltaY) === 1) {
        camScale -= 0.1
      }
      if (Math.sign(e.wheelDeltaY) === -1) {
        camScale += 0.1
      }

      cameraRef.current.scale.set(camScale, camScale, camScale)
    }

    // code to increment object.position.z
  })

  const { nodes, materials } = useGLTF('/models/Base_GLTF.glb')
  return (
    <>
      <OrthographicCamera
        ref={cameraRef}
        name='Camera'
        makeDefault={true}
        zoom={200}
        far={100000}
        near={-100000}
        up={[0, 1, 0]}
        position={[10, 5, 7]}
        rotation={[-0.78, 1.1, 0.72]}
        scale={1}
      />
      <sprite
        scale={0}
        position={[2, 1, 2]}
        OrthographicCamera
        onClick={move}
      />

      <group {...props} dispose={null} scale={0.01} position={[0, -1.4, 0]}>
        <group
          position={[20.31, 75.14, 4.32]}
          rotation={[0, 1.57, 0]}
          scale={0.5}
        >
          <group position={[0.66, -45.1, -4.32]} scale={0.4}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Beak-Beak'].geometry}
              material={materials.Beak}
            />
          </group>

          <group position={[0.66, -45.1, -4.32]} scale={0.4}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Eyes-Eyes'].geometry}
              material={materials.Eyes}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base.geometry}
            material={materials.Duck}
            position={[0.66, -45.1, -4.32]}
            scale={0.4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pants.geometry}
            material={materials.Eyes}
            position={[-0.34, -45.1, -4.32]}
            scale={[1.02, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shirt.geometry}
            material={materials.Shirt}
            position={[0.28, -0.85, -1.75]}
            rotation={[0, -1.57, 0]}
            scale={2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cap.geometry}
            material={materials.Cap}
            position={[1.02, 115.91, -3.52]}
          />
        </group>
        <group position={[91.23, 156.76, -71.65]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Holder1-Shop'].geometry}
            material={materials.Shop}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Holder1-White'].geometry}
            material={materials.White}
          />
        </group>
        <group position={[14.41, 23.94, 105.31]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Plants-Grass1'].geometry}
            material={materials['Grass.1']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Plants-Grass'].geometry}
            material={materials.Grass}
          />
        </group>
        <group
          position={[-90.62, 0, -24.19]}
          rotation={[-Math.PI, 0, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['TrashBin-Grass'].geometry}
            material={materials.Grass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['TrashBin-Metal_black'].geometry}
            material={materials.Metal_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheels.geometry}
            material={materials.Metal_black}
          />
        </group>
        <group
          position={[35.52, 82.07, 62.73]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.8}
        >
          <group position={[1.72, 173.25, 12.78]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Succulent-Grass1'].geometry}
              material={materials['Grass.1']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Succulent-Pots'].geometry}
              material={materials.Pots}
            />
          </group>
          <group position={[56.18, -102.59, -116.57]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Succulent-Grass'].geometry}
              material={materials.Grass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Succulent-Pots_1'].geometry}
              material={materials.Pots}
            />
          </group>
          <group position={[-57.9, -74.08, 103.79]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Succulent-Grass1_1'].geometry}
              material={materials['Grass.1']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Succulent-Pots_2'].geometry}
              material={materials.Pots}
            />
          </group>
        </group>
        <group
          position={[45.55, 149.48, 3.36]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[5.41, 5.41, 4.91]}
        >
          <group position={[2.32, 33.26, -24.39]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Grass'].geometry}
              material={materials.Grass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Soil'].geometry}
              material={materials.Soil}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Pots'].geometry}
              material={materials.Pots}
            />
          </group>
          <group position={[-15.82, -18.87, -25.75]} rotation={[0, 0, -0.79]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Grass_1'].geometry}
              material={materials.Grass}
            />
          </group>
          <group position={[-17.37, -29.78, -30.43]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Grass_2'].geometry}
              material={materials.Grass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Soil_1'].geometry}
              material={materials.Soil}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Pots_1'].geometry}
              material={materials.Pots}
            />
          </group>
          <group position={[-7.28, -10.03, 19.07]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Grass_3'].geometry}
              material={materials.Grass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Soil_2'].geometry}
              material={materials.Soil}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Pots_2'].geometry}
              material={materials.Pots}
            />
          </group>
          <group position={[7.28, 10.03, -19.63]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Grass_4'].geometry}
              material={materials.Grass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Soil_3'].geometry}
              material={materials.Soil}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Potted_plants-Pots_3'].geometry}
              material={materials.Pots}
            />
          </group>
        </group>
        <group position={[-168.54, 140, 134.86]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pole-Metal_black'].geometry}
            material={materials.Metal_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pole-Paper'].geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pole-Metal'].geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pole-Wood'].geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pole-White'].geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pole-White_1'].geometry}
            material={materials.White}
          />
        </group>
        <group position={[-168.54, 140, 134.86]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PoleMetal-Metal_black'].geometry}
            material={materials.Metal_black}
          />
        </group>
        <group position={[91.23, 156.76, 69.92]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Holder-Shop'].geometry}
            material={materials.Shop}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Holder-White'].geometry}
            material={materials.White}
          />
        </group>
        <group position={[136.03, 180.7, 62.71]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Roof-White'].geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Roof-Shop'].geometry}
            material={materials.Shop}
          />
        </group>
        <group position={[0, 34.59, 101.59]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Planter_1.geometry}
            material={nodes.Planter_1.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Planter-White'].geometry}
            material={materials.White}
          />
        </group>
        <group position={[-19.49, 57.85, -83.19]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Handle-White'].geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Handle-Handle'].geometry}
            material={materials.Handle}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Road.geometry}
          material={materials.Road}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stool.geometry}
          material={materials.Stool}
          position={[13.43, 6.22, 8.25]}
          scale={[1.3, 0.5, 1.3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Decals.geometry}
          material={materials.Stool}
          scale={0.4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Menu1.geometry}
          material={materials.Pots}
          position={[129.59, 0, -136.89]}
          rotation={[0, 0.92, 0]}
          scale={30}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mirror_Holder.geometry}
          material={materials['Grass.2']}
          position={[-157.25, 168.6, 145.41]}
          rotation={[0, -0.82, -Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mirror.geometry}
            material={materials.Metal}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grass_Detail.geometry}
          material={materials['Grass.1']}
          position={[28.17, -0.7, 9.84]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pipe.geometry}
          material={materials.Paper}
          position={[-2.45, 0, 1.92]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Boxes.geometry}
          material={materials.Box}
          position={[-23.41, 16.74, 17.35]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Menu.geometry}
          material={materials.Pots}
          position={[129.59, 0, -136.89]}
          rotation={[0, 0.92, 0]}
          scale={30}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AirCon.geometry}
          material={materials.White}
          position={[-72.95, 169.45, 48.74]}
          scale={0.2}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Holder_1.geometry}
            material={materials.Metal_black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rotator.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FanBlade.geometry}
            material={materials.Paper}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TrashBin1.geometry}
          material={materials['Grass.1']}
          position={[-90.62, 0, -24.19]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pots.geometry}
          material={materials.Pots}
          position={[-5.53, 24.54, 147.97]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.InnerShelf.geometry}
          material={materials.Wood}
          position={[-36.19, 142.18, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ShopWall.geometry}
          material={materials.Paper}
          position={[-55.31, 106.76, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wire.geometry}
          material={materials.Metal_black}
          position={[-168.54, 140, 134.86]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Straw.geometry}
          material={materials.White}
          position={[-0.08, 238.56, -38.82]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Soil.geometry}
          material={materials.Soil}
          position={[0, 34.59, 101.59]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wooden_Footer.geometry}
          material={materials.Wood}
          position={[79.98, 10.28, 33.07]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf.geometry}
          material={materials.White}
          position={[77.19, 88.16, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shop_Base.geometry}
          material={materials.Shop}
        />
      </group>
    </>
  )
}

useGLTF.preload('/models/Base_GLTF.glb')
